version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    image: node:18
    working_dir: /usr/src/app
    command: npx http-server -p 8080 -c-1
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
